### PR TITLE
ISSUE | What if GitHub using AI to validate repos?

### PR DESCRIPTION
**Pull request by sudo-do**
We all here pushing weird stuff to repo. Just wasting GitHub's storage & inode for vain.

What if GitHub using AI to validate active repositories?

I'm sure this repo is not cloned more than 50 times. How can this be an active and useful repo?

Also, if GitHub using AI to validate the thing is worth free copilot, those weird additions will have no change.

🤔

### CODE REVIEW

**Comment by sudo-do** [comment]
@InimicalPart

**Review by LimitlyAI — CHANGES_REQUESTED** [review]
I'm a smart bot and I understood this PR is not meant to add something new to the repo.

I'll keep my silence.

**Comment by InimicalPart** [comment]
We're not fully sure, the only thing we can do is try and see what happens, we also need to consider that if keeping it active requires a lot of attention from people, it might not be done and then we will never achieve our goal of giving people GitHub Copilot.

We're open to suggestions from people :), please email us at limitly@inimicalpart.com or ping me in a pull request :)

**Comment by sudo-do** [comment]
I'll try my change to get some info from GitHub about this.

**Comment by InimicalPart** [comment]
Please do! Let us know how it goes <3

**Comment by sudo-do** [comment]
They rejected to tell anything about this. Except: _It's an automatic process. GitHub support don't have visibility of how it works._

Do you know what repositories are awarded @InimicalPart

**Comment by InimicalPart** [comment]
I do not :(, but you can probably google and find out. I know big projects have it, but can't really point out which ones.

**Comment by InimicalPart** [comment]
I'm gonna close this pull request now. I've also re-activated the "issues" tab, so feel free to create something there if you find something :)

**Pull request closed without merging**
