### PR TITLE
Create Gelocg

### PR DESCRIPTION
**Pull request by Gelocg**

### CODE REVIEW

**Review by InimicalPart — CHANGES_REQUESTED** [review]
Hey there! You need to make a folder in the Contributors folder with your GitHub username and then put a file in there! It seems that you've put a file in the Contributors folder, please fix that and we can merge your pull request! ❤️

**Review by LimitlyAI — CHANGES_REQUESTED** [review]
Thank you for submitting your pull request! Unfortunately, before we can merge it, there are some changes that need to be made. Here's what you need to do:<br><br><ul><li>`/Contributors/Geolocg/Readme.md` - <i>It seems that the file you added is not in the correct folder. Please move the file to [`Contributors/Gelocg`](/Contributors/Gelocg).</i></li></ul><hr>Once you've made these changes, please request another review from me. I'll check the changes you've made and, if everything looks good, I'll merge your pull request. :stuck_out_tongue_winking_eye:<hr>If you're not sure what's wrong with the file, the "Files changed" tab at the top of this page (located roughly below and to the right of the pull request title) can help.It will show you all the files you've changed and what has changed. Files that shouldn't be edited should not be in that tab. The best way to ensure that your version is correct is to go to the repository, find the file, copy the contents, and make sure they match your version.<br><br>If you're still having trouble, please ping or request a review from `@InimicalPart` and `@1RB`, and we'll help you out as soon as possible.

**Review by LimitlyAI — APPROVED** [review]
<h1>Congratulations! Your pull request has been approved! :tada:</h1><p>Hey there, and welcome to the team, <b>@Gelocg</b>! Your pull request has been approved! :sparkles:<br> This means that you should receive an email invitation to collaborate very soon. In the meantime, here's what you can expect:<br><br>You now have write access to this repository, but all changes must be made through pull requests, and any changes you make must be restricted to your own folder. Please note that if we find that you've engaged in any of the following actions, we'll have to remove you as a collaborator:<ul><li>Editing labels on pull requests.</li><li>Adding reviews (incl. approve, changes requested) to other pull requests</li><li>Modifying other users' pull requests without their explicit permission.</li><li>Changing any settings that haven't been authorized by Limitly.</li><li>Attempting to circumvent Limitly's rules and terms of use.</li><li>Violating the <a href="/Limitly/Free-Copilot/blob/main/TERMS_OF_USE.md">terms of use</a>.</li></ul><hr><br>Please commit to your folder at least once every 31 days to keep the repository active and to allow other users access to Copilot. Failure to do so will result in the temporary removal of your collaborator access until you've committed again.<br><br>If you have any questions or concerns, please don't hesitate to reach out to us directly at <a href="mailto:limitly@inimicalpart.com">limitly@inimicalpart.com</a>.<br><br>We cannot express how thankful we are for your support on this project. It means <b> the world </b> to us! :heart:<br><br>- Limitly</p>

**Comment by sudo-do** [comment]
@InimicalPart You have pending change requests.

**Comment by InimicalPart** [comment]
@sudo-do do you own the Gelocg account?

**Comment by InimicalPart** [comment]
@sudo-do Please look at [this comment](https://github.com/Limitly/Free-Copilot/pull/19#issuecomment-1525036166)

**Pull request merged**
