### PR TITLE
Create Readme.md

### PR DESCRIPTION
**Pull request by Aurelien-SamS**

### CODE REVIEW

**Review by LimitlyAI — CHANGES_REQUESTED** [review]
_deleted_

**Comment by sudo-do** [comment]
@Aurelien-SamS You are welcome

**Comment by InimicalPart** [comment]
Hey @sudo-do! It is very kind of you to help others get their pull request merged, but please keep in mind that modifying others' pull requests is against one of our rules, we advise you not to modify others or we will have to remove your collaborator access :(

- Modifying other users' pull requests without their explicit permission.

**Comment by sudo-do** [comment]
@InimicalPart uh, Thanks for warning.

**Pull request merged**
